---
ingress:
  name: kube-ingress
  namespace: kube-system
  repo: kube-aliyun
  httpPort: 32080
  httpsPort: 32443

logs:
  controller:
    image: registry.cn-hangzhou.aliyuncs.com/log-service/alibabacloud-log-controller
    version: latest
  logtail:
    image: registry.cn-hangzhou.aliyuncs.com/log-service/logtail
    version: latest
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 100Mi
  projectName: kube-apollo-preprod
  endpoint: cn-hangzhou-intranet.log.aliyuncs.com
  machineGroupId: apollo-preprod


onboarding:
  name: onboarding
  namespace: platform
  repo: kube-aliyun
  container: ikerry/node-metrics
  containerPort: 8080
  version: v0.1.1
  dns_name: dev.gugecc.com
