---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    k8s-app: logtail-ds
    kubernetes.io/cluster-service: "true"
  name: logtail-readiness-check
  namespace: kube-system
data:
  check.sh: |-
    #!/usr/bin/env bash

    sleep 5
    flag=0
    while [[ $flag -eq 0 ]]
    do
      AccessKeySecret=$ALICLOUD_LOG_ACCESS_KEY_SECRET
      if [[ -z "${AccessKeySecret}" ]]; then
        sleep 2
      else
        flag=1
      fi
    done
