---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ingress.name}}
  namespace: {{ingress.namespace}}
  labels:
    app: {{ingress.name}}
    repo: {{ingress.repo}}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ingress.name}}
  labels:
    app: {{ingress.name}}
    repo: {{ingress.repo}}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - endpoints
      - nodes
      - pods
      - secrets
    verbs:
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "extensions"
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups:
      - "extensions"
    resources:
      - ingresses/status
    verbs:
      - update

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ingress.name}}
  labels:
    app: {{ingress.name}}
    repo: {{ingress.repo}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ingress.name}}
subjects:
  - kind: ServiceAccount
    name: {{ingress.name}}
    namespace: {{ingress.namespace}}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ingress.name}}
  namespace: {{ingress.namespace}}
  labels:
    app: {{ingress.name}}
    repo: {{ingress.repo}}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - pods
      - secrets
      - namespaces
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - configmaps
    resourceNames:
      - "ingress-nodeport-leader-nginx"
    verbs:
      - get
      - create
      - update
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create
      - update
  - apiGroups:
      - ""
    resources:
      - endpoints
    verbs:
      - get
      - create
      - update

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ingress.name}}
  namespace: {{ingress.namespace}}
  labels:
    app: {{ingress.name}}
    repo: {{ingress.repo}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ingress.name}}
subjects:
  - kind: ServiceAccount
    name: {{ingress.name}}
    namespace: {{ingress.namespace}}
